import os
import dotenv

VECTOR_STORE_PATH = os.getenv("VECTOR_STORE_PATH")
RAG_FILES_DIR = os.getenv("RAG_FILES_DIR")

AI_SYSTEM_PROMPT = os.getenv("AI_SYSTEM_PROMPT")
AI_CONTEXTUALIZE_PROMPT = os.getenv("AI_CONTEXTUALIZE_PROMPT")

REDIS_URL = os.getenv('CACHE_REDIS_URI')

AUTHENTICATION_API_KEY = os.getenv("AUTHENTICATION_API_KEY")
EVOLUTION_API_URL= os.getenv("EVOLUTION_API_URL")
EVOLUTION_INSTANCE_NAME = os.getenv("EVOLUTION_INSTANCE_NAME")

OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME")
OPENAI_MODEL_TEMPERATURE = os.getenv("OPENAI_MODEL_TEMPERATURE")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")