FROM python:3.13

WORKDIR /main

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY service_account.json /app/service_account.json

EXPOSE 8000

CMD uvicorn main:app --host 0.0.0.0 --port 8000
